export default [
  { name: "Dog" },
  { name: "Cat" },
  { name: "Lion" },
  { name: "Tiger" },
  { name: "Elephant" },
  { name: "Giraffe" },
  { name: "Monkey" },
  { name: "Bear" },
  { name: "Horse" },
  { name: "Cow" },
  { name: "Pig" },
  { name: "Sheep" },
  { name: "Goat" },
  { name: "Chicken" },
  { name: "Duck" },
  { name: "Goose" },
  { name: "Rabbit" },
  { name: "Mouse" },
  { name: "Rat" },
  { name: "Hamster" },
  { name: "Guinea Pig" },
  { name: "Parrot" },
  { name: "Owl" },
  { name: "Eagle" },
  { name: "Penguin" },
  { name: "Dolphin" },
  { name: "Whale" },
  { name: "Shark" },
  { name: "Octopus" },
  { name: "Seal" },
  { name: "Frog" },
  { name: "Toad" },
  { name: "Crocodile" },
  { name: "Alligator" },
  { name: "Snake" },
  { name: "Lizard" },
  { name: "Turtle" },
  { name: "Tortoise" },
  { name: "Fish" },
  { name: "Goldfish" },
  { name: "Crab" },
  { name: "Lobster" },
  { name: "Butterfly" },
  { name: "Bee" },
  { name: "Ant" },
  { name: "Spider" },
  { name: "Ladybug" },
  { name: "Dragonfly" },
  { name: "Snail" },
  { name: "Worm" },
  { name: "Bat" },
  { name: "Squirrel" },
  { name: "Hedgehog" },
  { name: "Deer" },
  { name: "Moose" },
  { name: "Kangaroo" },
  { name: "Koala" },
  { name: "Panda" },
  { name: "Camel" },
  { name: "Donkey" },
  { name: "Zebra" },
  { name: "Rhinoceros" },
  { name: "Hippopotamus" },
  { name: "Wolf" },
  { name: "Fox" },
  { name: "Leopard" },
  { name: "Cheetah" },
  { name: "Gorilla" },
  { name: "Chimpanzee" },
  { name: "Orangutan" },
  { name: "Peacock" },
  { name: "Turkey" },
  { name: "Swan" },
  { name: "Flamingo" },
  { name: "Pelican" },
  { name: "Seagull" },
  { name: "Woodpecker" },
  { name: "Crow" },
  { name: "Pigeon" },
  { name: "Sparrow" },
  { name: "Robin" },
  { name: "Blue Jay" },
  { name: "Cardinal" },
  { name: "Hawk" },
  { name: "Vulture" },
  { name: "Stork" },
  { name: "Emu" },
  { name: "Ostrich" },
  { name: "Armadillo" },
  { name: "Otter" },
  { name: "Beaver" },
  { name: "Raccoon" },
  { name: "Skunk" },
  { name: "Mole" },
  { name: "Porcupine" },
  { name: "Platypus" },
  { name: "Walrus" },
  { name: "Narwhal" },
  { name: "Jellyfish" },
  { name: "Starfish" },
  { name: "Seahorse" },
  { name: "Clownfish" },
  { name: "Swordfish" },
  { name: "Manta Ray" },
  { name: "Gazelle" },
  { name: "Buffalo" },
  { name: "Bison" },
  { name: "Yak" },
  { name: "Lynx" },
  { name: "Bobcat" },
  { name: "Cougar" },
  { name: "Jaguar" },
  { name: "Hyena" },
  { name: "Meerkat" },
  { name: "Wombat" },
  { name: "Sloth" },
  { name: "Tapir" },
  { name: "Okapi" },
  { name: "Aardvark" },
  { name: "Antelope" },
  { name: "Chinchilla" },
  { name: "Ferret" },
  { name: "Lemur" },
  { name: "Manatee" },
  { name: "Quokka" },
  { name: "Capybara" },
  { name: "Mongoose" },
  { name: "Ocelot" },
  { name: "Serval" },
  { name: "Tamarin" },
  { name: "Agouti" },
  { name: "Dik-dik" },
  { name: "Springbok" },
  { name: "Impala" },
  { name: "Bonobo" },
  { name: "Proboscis Monkey" },
  { name: "Gibbon" },
  { name: "Saki Monkey" },
  { name: "Uakari" },
  { name: "Howler Monkey" },
  { name: "Spider Monkey" },
  { name: "Tamarin Monkey" },
  { name: "Marmoset" },
  { name: "Bushbaby" },
  { name: "Colobus Monkey" },
  { name: "Mandrill" },
  { name: "Drill" },
  { name: "Baboon" },
  { name: "Gelada" },
  { name: "Patas Monkey" },
  { name: "Vervet Monkey" },
  { name: "Sifaka" },
  { name: "Indri" },
  { name: "Aye-aye" },
  { name: "Fossa" },
  { name: "Tenrec" },
  { name: "Solendon" },
  { name: "Numbat" },
  { name: "Quoll" },
  { name: "Bandicoot" },
  { name: "Bilby" },
  { name: "Tasmanian Devil" },
  { name: "Echidna" },
  { name: "Kakapo" },
  { name: "Kea" },
  { name: "Takahe" },
  { name: "Weka" },
  { name: "Kiwi" },
  { name: "Morepork" },
  { name: "Fantail" },
  { name: "Silvereye" },
  { name: "Bellbird" },
  { name: "Stitchbird" },
  { name: "Saddleback" },
  { name: "Kokako" },
  { name: "Huia" },
  { name: "Piopio" },
  { name: "Tui" },
  { name: "Hihi" },
  { name: "Rockhopper Penguin" },
  { name: "Emperor Penguin" },
  { name: "King Penguin" },
  { name: "Little Blue Penguin" },
  { name: "Fiordland Penguin" },
  { name: "Snares Penguin" },
  { name: "Erect-crested Penguin" },
  { name: "Yellow-eyed Penguin" },
  { name: "Magellanic Penguin" },
  { name: "Humboldt Penguin" },
  { name: "Galapagos Penguin" },
  { name: "African Penguin" },
  { name: "Chinstrap Penguin" },
  { name: "Gentoo Penguin" },
  { name: "Adelie Penguin" },
  { name: "Macaroni Penguin" },
  { name: "Royal Penguin" },
  { name: "Fairy Penguin" },
  { name: "White-flippered Penguin" },
  { name: "Northern Rockhopper Penguin" },
  { name: "Southern Rockhopper Penguin" },
  { name: "Eastern Rockhopper Penguin" },
  { name: "Western Rockhopper Penguin" },
  { name: "Northern Little Penguin" },
  { name: "Southern Little Penguin" },
  { name: "Australian Little Penguin" },
  { name: "New Zealand Little Penguin" },
  { name: "Tasmanian Little Penguin" },
  { name: "Antarctic Little Penguin" },
  { name: "Subantarctic Little Penguin" },
  { name: "South American Little Penguin" },
  { name: "African Little Penguin" },
  { name: "Galapagos Little Penguin" },
  { name: "Magellanic Little Penguin" },
  { name: "Humboldt Little Penguin" },
  { name: "Chinstrap Little Penguin" },
  { name: "Gentoo Little Penguin" },
  { name: "Adelie Little Penguin" },
  { name: "Macaroni Little Penguin" },
  { name: "Royal Little Penguin" },
  { name: "Fairy Little Penguin" },
  { name: "White-flippered Little Penguin" },
]; 